export const servicesHotel = [
  "Recepcion 24hs",
  "Servicio a la habitacion",
  "Restaurante & Bar",
  "Desayuno incluido",
  "Wi-Fi",
  "Lavanderia",
  "Estacionameinto",
  "Centro de negocios",
  "Piscina",
  "Gimnasio",
  "SPA",
  "Transporte al aeropuerto",
  "Actividades de entretenimiento",
  "Vigilacia",
  "Guarderia",
  "Adaptabilidad a personas con discapacidad",
];

export const servicesRoom = [
  "Cama comoda",
  "Baño privado",
  "TV",
  "Servicio a la habitacion",
  "Minibar",
  "Cafetera",
  "Escritorio",
  "Plancha",
  "Secador de pelo",
  "Telefono",
  "Toallas",
  "Ventanas insonorizadas",
];
